project:
  type: website

website:
  title: "NASCol - Network Analysis Software Collective"
  favicon: assets/favicon.ico
  description: "Network Analysis Software Collective"
  twitter-card: 
    title: "NASCol - Network Analysis Software Collective"
    description: "Network Analysis Software Collective"
    image: assets/logo/logo.png
    image-alt: NASC logo
  open-graph: 
    title: "NASCol - Network Analysis Software Collective"
    description: "Network Analysis Software Collective"
    image: assets/logo/logo.png
    image-alt: logo
  navbar:
    logo: assets/logo/logo_blank.png
    logo-alt: logo of NASCol
    right:
      - text: About us
        href: about.qmd
      - text: Packages
        href: packages/
      - text: Blog
        href: blog.qmd
      - text: Events
        menu:
          - text: NetSci 2024 Satellite Workshop
            href: https://netsci.nascol.net/
      - text: Discourse
        href: https://nascol.discourse.group/
      - icon: github
        href: https://github.com/nas-col/nascol-web
  page-footer:
    center:
      - text: "powered by Quarto"
        href: https://quarto.org
    right:
      - text: "Â© Copyright 2023 NASCol"
format:
  html:
    theme:
      light: [cosmo, nasc-light.scss]
      dark: [cosmo, nasc-dark.scss]
    css: styles.css 
execute:
  freeze: auto
